weaviate/weaviate-go-client

v2/test/graphql/graphql_test.go
v2/weaviate/graphql/explore_test.go
v2/weaviate/graphql/neartextbuilder.go

gh-15 Remove limit from nearText argument

---

.travis.yml
v2/test/graphql/graphql_test.go
v2/test/schema/schema_test.go
v2/weaviate/batch/objects.go
v2/weaviate/graphql/constants.go
v2/weaviate/graphql/explore_test.go
v2/weaviate/graphql/getquerybuilder.go
v2/weaviate/graphql/getquerybuilder_test.go
v2/weaviate/graphql/nearobjectbuilder.go
v2/weaviate/graphql/neartextbuilder.go

gh-18 Change get builder to use nearText builder

---

v2/weaviate/graphql/askbuilder.go
v2/weaviate/graphql/explore.go
v2/weaviate/graphql/explore_test.go
v2/weaviate/graphql/getquerybuilder.go
v2/weaviate/graphql/getquerybuilder_test.go
v2/weaviate/graphql/gql.go

gh-12 Add support for ask argument

---

v2/weaviate/graphql/askbuilder.go
v2/weaviate/graphql/getquerybuilder_test.go
v2/weaviate/graphql/neartextbuilder.go

gh-26 Add support for spellcheck module

---

v2/test/docker-compose.yaml
v2/test/schema/schema_test.go

gh-28 Update Weaviate test docker compose version

---

v2/test/data/data_test.go
v2/test/schema/schema_test.go
v2/test/testsuit/generics.go
v2/weaviate/data/creator.go

- Implement `WithVector` method on the `data.Creator` type.
- Write integration tests asserting correctness
- Fix typo found in comment
---
Closes #36

Feature: Create data object with custom vectors

---

v2/weaviate/graphql/askbuilder.go
v2/weaviate/graphql/getquerybuilder_test.go

gh-38 Add support for rerank parameter in ask argument

---

v2/test/data/data_test.go
v2/test/docker-compose.yaml
v2/test/schema/schema_test.go
v2/weaviate/data/checker.go
v2/weaviate/data/data.go
v2/weaviate/except/handling.go

gh-40 Add support for object check request

---

v2/test/schema/schema_test.go
v2/weaviate/schema/classGetter.go
v2/weaviate/schema/schema.go

gh-45 Add support for /v1/schema/{className}

---

v2/test/graphql/graphql_test.go
v2/weaviate/graphql/aggregate.go
v2/weaviate/graphql/aggregate_test.go

gh-47 Add support for where argument in Aggregate

---

v3/test/graphql/graphql_test.go
v3/weaviate/graphql/getquerybuilder.go
v3/weaviate/graphql/getquerybuilder_test.go
v3/weaviate/graphql/gql.go
v3/weaviate/graphql/groupbuilder.go
v3/weaviate/graphql/groupbuilder_test.go

gh-30 Add group filter builder

---

v3/test/graphql/graphql_test.go
v3/weaviate/graphql/aggregate.go
v3/weaviate/graphql/aggregate_test.go
v3/weaviate/graphql/constants.go
v3/weaviate/graphql/getquerybuilder.go
v3/weaviate/graphql/getquerybuilder_test.go
v3/weaviate/graphql/gql.go
v3/weaviate/graphql/wherebuilder.go
v3/weaviate/graphql/wherebuilder_test.go
v3/weaviate/graphql/wherefilter.go

gh-32 Add where filter builder

---

v3/test/graphql/graphql_test.go
v3/weaviate/graphql/aggregate.go
v3/weaviate/graphql/aggregate_test.go
v3/weaviate/graphql/fieldbuilder.go
v3/weaviate/graphql/fieldbuilder_test.go
v3/weaviate/graphql/getquerybuilder.go
v3/weaviate/graphql/getquerybuilder_test.go

gh-33 Add field field builder

---

readme.md

it has been determined!

---

v4/test/graphql/graphql_test.go
v4/test/testsuit/generics.go
v4/weaviate/filters/where.go
v4/weaviate/filters/where_test.go

To make the existing "Get" tests a bit more readable they have been
broken up into subtests that each focus on one concern. This makes the
diff a bit harder to read, but the overall test is much easier to read
now.

fix valueDate filter and test e2e

---

v4/weaviate/weaviate_client.go

Adds this warning on 19.1.2023

Add warning for upcoming move

---

.pre-commit-config.yaml

Adds precommit to the client. Usage is optional

Add precommit with gofumpt

---

test/misc/misc_test.go
weaviate/except/handling_test.go
weaviate/fault/error.go
weaviate/fault/error_test.go

Fix WeaviateClientError's Error method to return proper error message

---

weaviate/graphql/aggregate.go
weaviate/graphql/aggregate_test.go
weaviate/graphql/explore.go
weaviate/graphql/explore_test.go
weaviate/graphql/get.go
weaviate/graphql/get_test.go
weaviate/graphql/gql.go
weaviate/graphql/nearaudiobuilder.go
weaviate/graphql/nearaudiobuilder_test.go
weaviate/graphql/neardepthbuilder.go
weaviate/graphql/neardepthbuilder_test.go
weaviate/graphql/nearimagebuilder.go
weaviate/graphql/nearimagebuilder_test.go
weaviate/graphql/nearimubuilder.go
weaviate/graphql/nearimubuilder_test.go
weaviate/graphql/nearmediabuilder.go
weaviate/graphql/nearmediabuilder_test.go
weaviate/graphql/nearthermalbuilder.go
weaviate/graphql/nearthermalbuilder_test.go
weaviate/graphql/nearvideobuilder.go
weaviate/graphql/nearvideobuilder_test.go

adds support for `nearVideo`, `nearAudio`, `nearDepth`, `nearThermal`, `nearIMU`

adds near<media> support

---

test/schema/schema_test.go
weaviate/schema/classUpdater.go
weaviate/schema/schema.go

- Create `ClassUpdater` that will `PUT /schema/{class}` to update settings such as the `vectorIndexConfig`.
- Add new schema tests

ClassUpdater for Schema modifications

---

test/data/data_test.go
weaviate/data/updater.go

This PR adds support for updating object with custom vector
refer to #188

Support for updating object with custom vector

---

test/batch/batchCreateGRPC_test.go
test/graphql/graphql_test.go
test/testsuit/generics.go
weaviate/connection/grpc.go

This PR adds support for `cross-references` in `gRPC Batch API` calls.

Add support for cross references in gRPC Batch API

---

test/backup/backup_test.go
weaviate/backup/backup_creator.go
weaviate/backup/backup_restorer.go

Support compression config for backup, restore
Closes #208

Support backup & restore compression configuration

---

test/batch/batchCreateGRPC_named_vectors_test.go
test/batch/batchCreateGRPC_test.go
test/testsuit/generics.go

Run GRPC tests with auth enabled. Worked without problems :)

Add GRPC+auth test

---

test/client/startup_test.go
test/testsuit/generics.go
weaviate/connection/grpc.go
weaviate/connection/rest.go
weaviate/weaviate_client.go

Closes https://github.com/weaviate/weaviate-go-client/issues/224

Add grpc client init timeout with tests validating usage

---

README.md
test/backup/backup_test.go
test/batch/batchCreateGRPC_named_vectors_test.go
test/batch/batchCreateGRPC_test.go
test/batch/batchCreate_test.go
test/batch/batchDelete_test.go
test/classifications/classification_test.go
test/classifications/classification_with_where_test.go
test/cluster/nodes_test.go
test/contextionary/contextionary_test.go
test/data/data_test.go
test/data/reference_test.go
test/graphql/graphql_test.go
test/graphql/multi_target_near_vector_test.go
test/misc/misc_test.go
test/misc/misc_version_check_test.go
test/object_property_tests/autoschema_test.go
test/object_property_tests/batch_test.go
test/object_property_tests/data_test.go
test/object_property_tests/graphql_test.go
test/schema/schema_test.go
test/testsuit/generics.go
weaviate/grpc/batch/batch.go

- tests use GRPC again
- fix if no UUID provided

Grpc fixes

---

test/filters/testcases.go
test/graphql/graphql_test.go
test/search/grpc_search_test.go
test/testsuit/generics.go
weaviate/filters/where.go

Please enter the commit message for your changes. Lines starting

4/4 chore: adds GRPC where filter tests

---

test/backup/backup_test.go
weaviate/backup/backup_restorer.go

Introduce functionality to overwrite existing aliases when restoring from a backup.

Add support for overwriting aliases during backup restoration
